---
kind: pipeline
name: dart-dev

steps:
- name: dependencies
  image: google/dart:dev
  pull: true
  volumes:
  - name: cache
    path: /root/.pubcache
  commands:
    - dart --version
    - pub get
    - cat .packages

- name: lint
  image: google/dart:dev
  volumes:
  - name: cache
    path: /root/.pubcache
  commands:
    - ls /root
    - ls /root/.pubcache
    - dart --version
    - dartanalyzer .

- name: test
  image: google/dart:dev
  volumes:
  - name: cache
    path: /root/.pubcache
  commands:
    - pub run test

volumes:
- name: cache
  temp: {}
