---
kind: pipeline
name: dart-dev

steps:
- name: dependencies
  image: google/dart:dev
  pull: true
  commands:
    - dart --version
    - pub get

- name: lint
  image: google/dart:dev
  commands:
    - dart --version
    - dartanalyzer .

- name: test
  image: google/dart:dev
  commands:
    - pub run test
