name: http_next
version: 2.0.0-dev

description: HTTP request middleware for Dart
homepage: https://github.com/http-dart/http-next

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  mime: ^1.0.0
  typed_data: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
  shelf: ^1.0.0
  stream_channel: ^2.1.0
  test: ^1.16.0
